DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id VARCHAR(36) PRIMARY KEY,
  email VARCHAR(30) NOT NULL,
  password CHAR(60) NOT NULL,
  refreshToken TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);